"use client";

import { useEffect, useMemo, useState } from "react";
import { ArrowUpRight, Check, ChevronDown, Menu, ShieldCheck, X } from "lucide-react";
import { sessions, slots, type Slot } from "@/lib/schedule";

type Reservation = { id?: number; code: string; slotId: string; parentName: string; phone: string; childName: string; childAge: string; childGender?: string; childYear: string; attendees: number; status: string; date?: string; time?: string; track?: string; sessionId?: string };
const contentSections = [["01", "New York English가\n생각하는 영어교육", "단순히 영어 100% 환경에 노출되는 것을 넘어, 듣고 이해하고, 읽고 말하고 쓰는 힘이 어떻게 연결되어야 하는지 설명드립니다."], ["02", "연령 · 연차별 교육과정", "5세의 첫 영어 시작부터 6세, 7세 그리고 초등 과정까지, 아이의 시작 시점과 학습 연차에 따라 무엇을 배우고 어떻게 성장하는지 보여드립니다."], ["03", "New York English Curriculum", "미국교과서인 Wonders와 뉴욕잉글리쉬의 자체 교재인 New York Dictionary · New York Phonics · New York Wonder How · New York Wonder Why를 기반으로 한 체계적이고 탄탄한 커리큘럼을 소개합니다."], ["04", "유치부에서 초등부까지의 성장 로드맵", "영어유치부에서 끝나지 않고 초등부까지 이어지는 장기적인 영어 성장 로드맵을 그려드립니다."], ["05", "수업과 평가, 그리고 아이의 관리", "아이들의 Speaking, Reading, Writing, Vocabulary와 학습 과정을 어떻게 관찰하고 평가하며, 학부모님께 어떻게 전달하는지 안내드립니다."], ["06", "Q&A", "설명 후에는 각 가정에서 궁금하셨던 내용을 충분히 질문하실 수 있는 시간을 마련합니다."]];
const logo = <img className="header-logo" src="/new-york-english-logo-transparent.png" alt="New York English" />;

function SlotPicker({ value, onChange, requestedSession }: { value: Slot | null; onChange: (slot: Slot | null) => void; requestedSession: string }) {
  const [track, setTrack] = useState<Slot["track"]>("신규생");
  const [sessionFilter, setSessionFilter] = useState("all");
  const [booked, setBooked] = useState<Record<string, number>>({});
  useEffect(() => { fetch("/api/availability").then((response) => response.json() as Promise<{ availability?: Record<string, number> }>).then((payload) => setBooked(payload.availability ?? {})).catch(() => undefined); }, []);
  useEffect(() => { setSessionFilter(requestedSession); }, [requestedSession]);
  const visible = slots.filter((slot) => slot.track === track && (sessionFilter === "all" || slot.sessionId === sessionFilter));
  const groups = useMemo(() => Array.from(new Set(visible.map((slot) => slot.date))), [visible]);
  return <div className="picker-stack"><div className="track-toggle" role="tablist" aria-label="예약 대상 선택">{(["신규생", "재원생 동생"] as const).map((item) => <button key={item} className={track === item ? "active" : ""} onClick={() => { setTrack(item); setSessionFilter("all"); onChange(null); }} role="tab" aria-selected={track === item}>{item}</button>)}</div>{track === "재원생 동생" && <p className="track-note">재원생 동생을 위해, 한 타임 한 가족만을 위한 1:1 맞춤 상담으로 조금 더 특별하게 준비했습니다.</p>}{track === "신규생" && <div className="session-filter"><button className={sessionFilter === "all" ? "active" : ""} onClick={() => { setSessionFilter("all"); onChange(null); }}>전체 세션</button>{sessions.map((session) => <button key={session.id} className={sessionFilter === session.id ? "active" : ""} onClick={() => { setSessionFilter(session.id); onChange(null); }}>{session.id}</button>)}</div>}<div className="date-grid">{groups.map((date) => <div className="date-group" key={date}><p>{visible.find((slot) => slot.date === date)?.dateLabel}</p><div className="time-row">{visible.filter((slot) => slot.date === date).map((slot) => { const remaining = Math.max(0, slot.capacity - (booked[slot.id] ?? 0)); return <button key={slot.id} disabled={remaining === 0} className={`time-chip ${value?.id === slot.id ? "selected" : ""}`} onClick={() => onChange(slot)}><strong>{slot.time}</strong><span>{slot.sessionId === "sibling" ? "재원생 동생 전용" : `${slot.sessionId} 세션`}</span><small>{remaining ? `잔여 ${remaining}석` : "예약 마감"}</small></button>; })}</div></div>)}</div></div>;
}

function BookingDialog({ slot, close }: { slot: Slot; close: () => void }) {
  const [done, setDone] = useState<Reservation | null>(null); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  const [form, setForm] = useState({ parentName: "", phone: "", childName: "", childAge: "", childGender: "", childYear: slot.sessionId === "sibling" ? "재원생 동생" : slot.sessionId, attendees: 1, consent: false });
  const field = (key: keyof typeof form, value: string | number | boolean) => setForm((current) => ({ ...current, [key]: value }));
  const returnToProgram = () => { close(); window.setTimeout(() => document.getElementById("program")?.scrollIntoView({ behavior: "smooth", block: "start" }), 80); };
  async function submit(event: React.FormEvent) { event.preventDefault(); setError(""); if (!form.consent) return setError("개인정보 수집 및 이용에 동의해주세요."); setBusy(true); try { const response = await fetch("/api/reservations", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ slotId: slot.id, ...form }) }); const payload = await response.json() as { error?: string; reservation: Reservation; reservations: Reservation[] }; if (!response.ok) throw new Error(payload.error || "예약을 완료하지 못했습니다."); setDone(payload.reservation); } catch (cause) { setError(cause instanceof Error ? cause.message : "예약을 완료하지 못했습니다."); } finally { setBusy(false); } }
  return <div className="modal-backdrop" onMouseDown={(event) => event.target === event.currentTarget && close()}><div className="booking-modal" role="dialog" aria-modal="true" aria-labelledby="booking-title"><button className="icon-button modal-close" onClick={close} aria-label="닫기"><X size={20} /></button>{done ? <div className="success-state"><span className="success-icon"><Check size={28} /></span><p className="kicker">Reservation confirmed</p><h2 id="booking-title">예약이 완료되었습니다.</h2><p>아이의 시작점에 맞는 설명회 자리를 준비해두겠습니다.</p><div className="confirmation-card"><span>예약번호</span><strong>{done.code}</strong><span>날짜 · {slot.dateLabel}</span><span>시간 · {slot.time}</span><span>세션 · {slot.track} · {slot.sessionId === "sibling" ? "재원생 동생" : `${slot.sessionId} 세션`}</span><span>참석 인원 · {done.attendees}명</span></div><button className="primary-button full" onClick={returnToProgram}>확인</button></div> : <><p className="kicker">Reserve your seat</p><h2 id="booking-title">{slot.dateLabel}<br /><em>{slot.time}</em>에 만나요.</h2><p className="modal-lede">{slot.track} · {slot.sessionId === "sibling" ? "재원생 동생" : `${slot.sessionId} 세션`} · 최대 {slot.capacity}명</p><form onSubmit={submit} className="booking-form"><div className="form-grid"><label>보호자명<input required value={form.parentName} onChange={(e) => field("parentName", e.target.value)} placeholder="성함을 입력해주세요" /></label><label>연락처<input required value={form.phone} onChange={(e) => field("phone", e.target.value)} placeholder="010-0000-0000" inputMode="tel" /></label><label>자녀명<input required value={form.childName} onChange={(e) => field("childName", e.target.value)} placeholder="아이 이름을 입력해주세요" /></label><label>자녀 연령<input required value={form.childAge} onChange={(e) => field("childAge", e.target.value)} placeholder="예: 6세" /></label><label>자녀 성별<select required value={form.childGender} onChange={(e) => field("childGender", e.target.value)}><option value="">선택해주세요</option><option value="남아">남아</option><option value="여아">여아</option></select></label><label>영어 학습 연차<input required value={form.childYear} onChange={(e) => field("childYear", e.target.value)} placeholder="예: 1년차" /></label><label>참석 인원<select value={form.attendees} onChange={(e) => field("attendees", Number(e.target.value))}>{Array.from({ length: Math.min(slot.capacity, 2) }, (_, index) => <option key={index + 1} value={index + 1}>{index + 1}명</option>)}</select></label></div><label className="consent"><input type="checkbox" checked={form.consent} onChange={(e) => field("consent", e.target.checked)} /><span>예약 확인을 위해 입력한 개인정보를 수집·이용하는 데 동의합니다.</span></label>{error && <p className="form-error" role="alert">{error}</p>}<button className="primary-button full" disabled={busy}>{busy ? "예약 처리 중…" : "이 자리 예약하기"}<ArrowUpRight size={17} /></button></form></>}</div></div>;
}

export function HomePage() {
  const [selectedSlot, setSelectedSlot] = useState<Slot | null>(null); const [bookingSlot, setBookingSlot] = useState<Slot | null>(null); const [requestedSession, setRequestedSession] = useState("all"); const [mobileMenu, setMobileMenu] = useState(false);
  return <main><header className="site-header"><a href="#top" className="logo-link">{logo}</a><nav className={mobileMenu ? "open" : ""}><a href="#sessions" onClick={() => setMobileMenu(false)}>우리 아이 세션</a><a href="#program" onClick={() => setMobileMenu(false)}>설명회 내용</a><a href="#reserve" onClick={() => setMobileMenu(false)}>예약 안내</a></nav><a className="header-cta" href="#reserve">좌석 예약하기 <ArrowUpRight size={16} /></a><button className="icon-button mobile-menu" onClick={() => setMobileMenu((value) => !value)} aria-label="메뉴"><Menu size={22} /></button></header>
    <section className="hero" id="top"><div className="hero-copy"><p className="eyebrow light hero-event-title">2027 New York English 입학 설명회</p><h1>같은 나이라도,<br /><em>영어를 시작한 시점에 따라</em><br />필요한 교육은 다릅니다.</h1><p className="hero-description">아이의 연령과 영어 학습 연차에 따라<br className="desktop-only" /> 서로 다른 교육과정과 성장 경로를 설계합니다.</p><a className="hero-button" href="#sessions">우리 아이에게 맞는 세션 확인하기 <ArrowUpRight size={18} /></a></div><div className="hero-seal"><img src="/new-york-english-logo-transparent.png" alt="New York English 로고" /></div><div className="hero-note"><span>01</span><p>Age · Experience<br /><strong>Different starting points.<br />Different roadmaps.</strong></p></div><div className="hero-bottom"><span>Admissions briefing</span></div></section>
    <section className="intro section-pad"><div className="section-label">Why different</div><div className="intro-grid"><h2><span><em>아이마다 시작점이 다르기에,</em></span><span>설명회도 달라야 합니다.</span></h2><div><p>영어를 처음 시작하는 시점과 지금까지 쌓아온 영어 경험에 따라 아이에게 필요한 교육의 순서와 깊이는 달라집니다.</p><p>New York English에서는 모든 연령을 한 번에 설명하지 않습니다. 각 세션에서 지금 어디에서 시작하고, 앞으로 어떻게 성장하게 되는지를 연령과 학습 연차에 맞춰 안내드립니다.</p></div></div></section>
    <section className="sessions-section section-pad" id="sessions"><div className="section-heading"><div><div className="section-label">Choose your session</div><h2>우리 아이에게<br /><em>맞는 세션</em></h2></div><p>아이의 시작점을 선택하면<br />가능한 설명회 일정을 확인할 수 있습니다.</p></div><div className="session-grid">{sessions.map((session, index) => <article className="session-card" key={session.id}><div className="card-heading"><span>0{index + 1}</span><h3>{session.eyebrow}</h3></div><p className="session-audience">{session.audience}</p><p>{session.description}</p><a href="#reserve" className="text-link" onClick={() => { setRequestedSession(session.id); setSelectedSlot(null); }}>세션 일정 보기 <ArrowUpRight size={16} /></a></article>)}</div></section>
    <section className="program-section section-pad" id="program"><div className="program-intro"><div className="section-label light">Inside the session</div><h2>이번 설명회에서<br /><em>만나보실 내용</em></h2><p>가르치는 것에서 멈추지 않고, 아이가 어디까지 성장하게 될지 함께 보여드립니다.</p></div><div className="content-list">{contentSections.map(([number, title, description]) => <div className="content-row" key={number}><span>{number}</span><div><h3>{title}</h3><p>{description}</p></div><ChevronDown size={18} /></div>)}</div></section>
    <section className="curriculum section-pad"><div className="curriculum-copy"><div className="section-label">Our curriculum</div><h2>하나의 교재가 아닌,<br /><em>연결되는 시스템</em></h2><p>미국 교과서인 Wonders와 New York English 자체 교재를 기반으로, 언어의 기초부터 읽기·문법·쓰기까지 단계적으로 확장되는 체계적인 커리큘럼입니다.</p></div><div className="curriculum-architecture"><div className="architecture-topline"><span>NEW YORK ENGLISH CURRICULUM</span><span>CONNECTED LEARNING SYSTEM</span></div><div className="curriculum-flow"><div className="flow-track"><div className="flow-node flow-phonics"><span>01 · SOUND</span><strong>New York<br />Phonics</strong><small>소리와 읽기의 기반</small></div><div className="flow-connector" /><div className="flow-node flow-how"><span>02 · BUILD</span><strong>New York<br />Wonder How</strong><div className="module-list"><em>Wonder How Voca</em><em>Wonder How Reading</em><em>Wonder How Grammar</em></div></div><div className="flow-connector" /><div className="flow-node flow-wonders"><span>03 · TEXT</span><strong>Wonders</strong><small>미국 교과서 기반의 이해와 사고</small></div><div className="flow-connector" /><div className="flow-node flow-why"><span>04 · THINK</span><strong>New York<br />Wonder Why</strong><div className="module-list"><em>Wonder Why Voca</em><em>Wonder Why Reading</em><em>Wonder Why Grammar</em><em>Wonder Why Writing</em></div></div></div><div className="dictionary-base"><span>CORE FOUNDATION · ALL STAGES</span><strong>New York Dictionary</strong><small>500개 주제 · 약 6,000개 실용 어휘로 쌓는 전 과정 공통 어휘 기반</small></div></div><div className="curriculum-stages"><div className="stages-label">FOUNDATION <i>→</i> EXPANSION <i>→</i> APPLICATION</div><div className="stage-grid"><div><span>01</span><strong>FOUNDATION</strong><small>어휘 · 소리</small></div><div><span>02</span><strong>STRUCTURE</strong><small>문장 · 문법</small></div><div><span>03</span><strong>EXPANSION</strong><small>읽기 · 이해</small></div><div><span>04</span><strong>APPLICATION</strong><small>사고 · 표현</small></div><div><span>05</span><strong>EXPRESSION</strong><small>쓰기 · 완성</small></div></div></div><div className="architecture-caption"><span />각 교재와 영역은 분리되지 않고, 하나의 학습 흐름 안에서 다음 단계로 이어집니다.</div></div></section>
    <section className="director section-pad"><div className="director-photo"><img src="/hailey-director.jpg" alt="New York English Hailey 원장" /></div><div><div className="section-label">Presented by Hailey</div><h2><span>12년의 영어 교육 경험을 바탕으로,</span><span><em>Hailey 원장이 직접 진행합니다.</em></span></h2><p>Hailey 원장님은 천안에서 12년째 New York English를 운영하며 유치부·초등부 교육과정과 자체 커리큘럼을 직접 설계하고 운영하고 있습니다.</p><p>이번 설명회에서는 단순히 어떤 과목과 교재를 사용하는지가 아니라, Hailey 원장님이 다년간 영어교육 현장에서 경험한 노하우를 토대로 <strong>왜 이 시기에 이 교육이 필요한지, 그리고 다음 단계와 어떻게 연결되는지</strong>를 각 연령과 학습 연차에 맞춰 직접 설명드립니다.</p></div></section>
    <section className="visit section-pad"><div className="section-label">Before your visit</div><div className="visit-grid"><h2>설명회에 오기 전,<br /><em>확인해주세요.</em></h2><div className="visit-points"><div><span>01</span><p>이번 입학 설명회는 보호자만 참석 가능합니다.</p></div><div><span>02</span><p>아버님과 어머님이 함께 참석하시는 경우 2개의 좌석으로 예약됩니다.</p></div><div><span>03</span><p>각 세션은 아이의 시작점에 맞춘 깊이 있는 상담과 충분한 질의응답을 위해, 한정된 좌석만 운영됩니다.</p></div><div><span>04</span><p>원활한 진행을 위해 예약 시간 10분 전까지 도착해 주세요.</p></div></div></div></section>
    <section className="reserve-section section-pad" id="reserve"><div className="reserve-header"><div className="section-label light">By reservation only</div><h2><span>우리 아이에게 맞는</span><span><em>자리를 예약하세요.</em></span></h2><p>각 세션은 정해진 좌석만 운영됩니다. 아이의 시작점에 맞는 교육과정을 충분히 설명드리고 충분한 질의응답 시간을 마련하기 위해 한 회차에 많은 인원을 받지 않습니다.</p></div><div className="reserve-panel"><div className="reserve-panel-top"><div><p className="kicker">Choose a date & time</p><h3>참석 가능한 일정을<br />선택해주세요.</h3></div><div className="availability"><span className="availability-dot" />잔여 좌석은 실시간으로 안내됩니다.</div></div><SlotPicker value={selectedSlot} onChange={setSelectedSlot} requestedSession={requestedSession} /><button className="primary-button reserve-submit" disabled={!selectedSlot} onClick={() => selectedSlot && setBookingSlot(selectedSlot)}>{selectedSlot ? `${selectedSlot.dateLabel} · ${selectedSlot.time} 예약하기` : "먼저 일정을 선택해주세요"}<ArrowUpRight size={17} /></button></div><p className="reserve-footnote"><ShieldCheck size={16} /> 보호자만 참석 가능합니다. 두 분이 함께 참석하시는 경우 2개의 좌석으로 예약됩니다.</p></section>
    <section className="closing"><div className="closing-ring" /><p className="eyebrow light">Your Child.<br className="mobile-only" /> Their Starting Point. Their Roadmap</p><h2>우리 아이에게 맞는<br /><em>영어 성장의 방향</em>을<br />만나 보세요.</h2><p className="closing-signature">New York English</p></section><footer className="site-footer"><a href="#top" className="footer-brand" aria-label="New York English 홈으로 이동"><img src="/new-york-english-logo-transparent.png" alt="New York English 로고" /></a><div className="footer-copy"><p>2027학년도 New York English 입학 설명회</p><p>문의 041-562-0011</p></div><span>© 2026 New York English</span></footer>{bookingSlot && <BookingDialog slot={bookingSlot} close={() => setBookingSlot(null)} />}</main>;
}

export function AdminPage() {
  const [password, setPassword] = useState(""); const [authorized, setAuthorized] = useState(false); const [rows, setRows] = useState<Reservation[]>([]); const [error, setError] = useState(""); const [loaded, setLoaded] = useState(false); const [sessionFilter, setSessionFilter] = useState("all"); const [dateFilter, setDateFilter] = useState("all");
  async function load() { try { const response = await fetch("/api/reservations", { headers: { "x-admin-password": password } }); const payload = await response.json() as { error?: string; reservation: Reservation; reservations: Reservation[] }; if (!response.ok) throw new Error(payload.error); setRows(payload.reservations); setLoaded(true); setAuthorized(true); setError(""); } catch (cause) { setError(cause instanceof Error ? cause.message : "예약 목록을 불러오지 못했습니다."); } }
  async function unlock(event: React.FormEvent) { event.preventDefault(); await load(); }
  async function cancel(id?: number) { if (!id || !confirm("이 예약을 취소할까요?")) return; try { const response = await fetch(`/api/reservations/${id}`, { method: "PATCH", headers: { "content-type": "application/json", "x-admin-password": password }, body: JSON.stringify({ status: "cancelled" }) }); const payload = await response.json() as { error?: string; reservation: Reservation; reservations: Reservation[] }; if (!response.ok) throw new Error(payload.error); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : "취소 처리에 실패했습니다."); } }
  const confirmedRows = rows.filter((row) => row.status === "confirmed");
  const filteredRows = rows.filter((row) => (sessionFilter === "all" || row.sessionId === sessionFilter) && (dateFilter === "all" || row.date === dateFilter));
  const totalAttendees = confirmedRows.reduce((total, row) => total + Number(row.attendees || 0), 0);
  const dateSummary = Array.from(new Set(rows.map((row) => row.date).filter(Boolean))).map((date) => { const dateRows = confirmedRows.filter((row) => row.date === date); return { date, reservations: dateRows.length, attendees: dateRows.reduce((total, row) => total + Number(row.attendees || 0), 0) }; });
  if (!authorized) return <main className="admin-page"><header className="admin-header">{logo}<span>예약 관리</span></header><section className="admin-shell admin-login"><div className="section-label">Private admin</div><h1>관리자 확인</h1><p>예약 정보를 확인하려면 관리자 비밀번호를 입력해주세요.</p><form onSubmit={unlock} className="admin-login-form"><label htmlFor="admin-password">비밀번호<input id="admin-password" type="password" value={password} onChange={(event) => setPassword(event.target.value)} autoFocus /></label><button className="primary-button" type="submit">관리자 페이지 열기</button></form>{error && <p className="form-error">{error}</p>}</section></main>;
  return <main className="admin-page"><header className="admin-header">{logo}<span>예약 관리</span></header><section className="admin-shell"><div className="section-label">Private admin</div><h1>입학 설명회 예약 목록</h1><p>비공개 관리자 화면입니다. 운영팀에서 예약 상태와 참석 인원을 확인하세요.</p><button className="primary-button" onClick={load}>{loaded ? "새로고침" : "예약 목록 불러오기"}</button>{error && <p className="form-error">{error}</p>}{loaded && <><div className="admin-stats"><div><span>확정 예약</span><strong>{confirmedRows.length}건</strong></div><div><span>총 신청 인원</span><strong>{totalAttendees}명</strong></div><div><span>취소 예약</span><strong>{rows.filter((row) => row.status === "cancelled").length}건</strong></div></div><div className="admin-filters"><label>연차별 보기<select value={sessionFilter} onChange={(event) => setSessionFilter(event.target.value)}><option value="all">전체 연차</option><option value="5-1">5세 · 1년차</option><option value="6-1">6세 · 1년차</option><option value="7-1">7세 · 1년차</option><option value="6-2">6세 · 2년차</option><option value="7-2">7세 · 2년차</option><option value="7-3">7세 · 3년차</option><option value="sibling">재원생 동생</option></select></label><label>날짜별 보기<select value={dateFilter} onChange={(event) => setDateFilter(event.target.value)}><option value="all">전체 날짜</option>{Array.from(new Set(rows.map((row) => row.date).filter(Boolean))).map((date) => <option key={date} value={date}>{date}</option>)}</select></label></div><div className="admin-date-summary"><h2>날짜별 예약 현황</h2><div>{dateSummary.map((item) => <span key={item.date}>{item.date}<strong>{item.reservations}건 · {item.attendees}명</strong></span>)}</div></div><div className="admin-table-wrap"><table><thead><tr><th>일정</th><th>세션</th><th>보호자 / 자녀</th><th>연락처</th><th>인원</th><th>상태</th><th /></tr></thead><tbody>{filteredRows.map((row) => <tr key={row.id}><td>{row.date}<br />{row.time}</td><td>{row.track}<br /><strong>{row.sessionId}</strong></td><td>{row.parentName}<br />{row.childName} · {row.childAge}</td><td>{row.phone}</td><td>{row.attendees}명</td><td><span className={`status ${row.status}`}>{row.status === "confirmed" ? "예약 완료" : "취소"}</span></td><td>{row.status === "confirmed" && <button className="small-button" onClick={() => cancel(row.id)}>취소 처리</button>}</td></tr>)}</tbody></table>{filteredRows.length === 0 && <p className="empty-state">조건에 맞는 예약이 없습니다.</p>}</div></>}</section></main>;
}

export default HomePage;
